apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: hello
      labels:
        env: dev
    spec:
      containers:
      - name: hello
        image: ghcr.io/rithik-sandron/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
