apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    env: dev
spec:
  containers:
  - name: hello
    image: ghcr.io/rithik-sandron/hello:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred
  envFrom:
  - configMapRef:
    name: hello-config